{{- if and (not .Values.awsRole) (and .Values.awsAccessKeyId .Values.awsSecretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    fluentd-cloudwatch.service: {{ .Values.name }}
type: Opaque
data:
{{- if .Values.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.awsAccessKeyId | b64enc }}
{{- end }}
{{- if .Values.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.awsSecretAccessKey | b64enc }}
{{- end }}
{{- end }}